services:
  backend:
    build:
      context: ./peerconnect
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge