services:
  backend:
    build:
      context: ./peerconnect
      dockerfile: Dockerfile.backend
    expose:
      - "8080"
      - "49152-65535"
    ports:
      - "8080:8080"   # Added to allow host access to backend
    networks:
      - app-network

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
